news_research_task:
  description: >
    Buscar a última notícia publicada em cada uma das fontes confiáveis listadas e em perfis de especialistas no LinkedIn. 
    Não é necessário verificar a data neste estágio. Cada notícia deve conter o título, um trecho inicial (quando disponível) e o link direto da fonte.
  expected_output: >
    Uma lista com a notícia mais recente de cada fonte, contendo:
    - Título
    - Trecho inicial (ou subtítulo, se houver)
    - URL da fonte original
  agent: news_seeker

news_cleaning_task:
  description: >
    Verificar a data de cada notícia recebida e filtrar apenas aquelas publicadas no útlimo mês. 
    Descartar qualquer notícia fora desse intervalo. Não modificar o conteúdo.
  expected_output: >
    Uma lista apenas com notícias válidas (até útlimo mês), contendo:
    - Título
    - Subtítulo ou trecho inicial
    - Data de publicação confirmada
    - URL da fonte original
  agent: news_cleaner

news_reporting_task:
  description: >
    Para cada notícia válida recebida, gerar um resumo estruturado contendo:
    - Título
    - Subtítulo (ou trecho inicial da notícia)
    - Resumo do conteúdo (em até 5 frases)
    - Data de publicação
    - Link da fonte
  expected_output: >
    Um conjunto de resumos detalhados e organizados para cada notícia, com:
    - Título
    - Subtítulo
    - Resumo do conteúdo
    - Data
    - Fonte (URL)
  agent: reporting_analyst
